### ISSUE TITLE
How to set the html form name attribute to the textarea for Backend processing

### ISSUE THREAD

**Issue by hasentopf** [ankurk91/vue-trumbowyg#10]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ X ] Other, please describe
```

**Tell about your platform**
* Trumbowyg version : 2.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : 3.1.2

**Current behavior**
I'm using your Component in a Laravel PHP app and struggling with the name attribute for the submitted textarea.

**Minimal reproduction of the problem with instructions**
In my current component I use a prop to set the textarea[name] and the v-model to sync the trumbowyg content:
```
<template>
    <div class="trumbowygComponent">
        <trumbowyg :config="config" v-model="content" class="form-control"></trumbowyg>
        <textarea :name="targetInput" v-model="content" class="hidden"></textarea>
    </div>
</template>

<script>
    // Import this component
    import trumbowyg from 'vue-trumbowyg';

    // Import editor css
    import 'trumbowyg/dist/ui/trumbowyg.css';

    export default {
        props: {
            targetInput: {
                type: String,
                default: 'content'
            }
        },
        data () {
            return {
                content: '',
                config:{
                    lang: 'de'
                }
            }
        },
        components: {
            trumbowyg
        }
    }
</script>
```

**Expected behavior**
A "name" parameter for your component, which add this to the trumbowyg-textarea:
`<trumbowyg :config="config" v-model="content" class="form-control" :name="targetInput"></trumbowyg>`
`<textarea name="content_for_laravel" class="form-control trumbowyg-textarea" tabindex="-1" style="height: 260px;"></textarea>`

**Comment by ankurk91** [comment]
You can check this JSFiddle
https://jsfiddle.net/d6pr6fop/1/

Actually the component will render textarea for you. You no need to add this in your html.

```html
<trumbowyg name="textarea-name-goes-here" v-model="content" :config="config" class="editor"></trumbowyg>
```

**Comment by hasentopf** [comment]
Thanks! So simple! Great!
