### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by thomaswoj** [ankurk91/vue-trumbowyg#11]
Hi Ankurk91,

My trumbowyg icons appear to be missing. 

I have installed via npm in laravel 5.6.7:

"trumbowyg": {
            "version": "2.9.4",
 "vue-trumbowyg": {
            "version": "3.1.2",

-----------------------------

**Webpack file:**
```js
mix.autoload({
    'jquery': ['$', 'window.jQuery', 'jQuery'],
    'vue': ['Vue','window.Vue'],
})

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

mix.copyDirectory('node_modules/trumbowyg', 'public/trumbowyg');
```
-------------------------------

**vue component:**
```html
<template>
    <div>
        <trumbowyg v-model="content"></trumbowyg>
    </div>
</template>

<script>
    // Import this component
    import trumbowyg from 'vue-trumbowyg';

    // Import editor css
    import 'trumbowyg/dist/ui/trumbowyg.css';

    import svgIcons from 'trumbowyg/dist/ui/icons.svg';


    export default {
        data () {
            return {
                content: '',
            }
        },
        components: {
            trumbowyg
        }
    }
</script>
```
----------------------------

Still nothing, any ideas? 

Thanks,

Tom

**Comment by ankurk91** [comment]
May in know your Laravel mix version, i think you are using v2.x ?

**Comment by thomaswoj** [comment]
Yup, 

"laravel-mix": {
            "version": "2.0.0",

**Comment by ankurk91** [comment]
I am looking into it.
Just to let you know, you no need to import ` svg` icons, the component is already doing this for you.

**Comment by thomaswoj** [comment]
Thanks 👍

**Comment by ankurk91** [comment]
And make sure you have `jquery` installed

**Comment by ankurk91** [comment]
To be honest i have not tested it with Laravel mix v2.0
v2.0 handles svg files differently now.
https://github.com/JeffreyWay/laravel-mix/pull/1367

Do you see any errors in console ?
Everything else in editor is loading properly and just icons are missing ?

**Comment by thomaswoj** [comment]
No errors in console, 

But looking at the icons.svg the file looks small/empty, should there be data inside? 

![image](https://user-images.githubusercontent.com/34551337/36945806-32270696-1fab-11e8-92dc-7f391a91314f.png)

**Comment by ankurk91** [comment]
Ok,
A quick workaround is to pass your custom svg icon file path via prop.

```html
 <trumbowyg
              v-model="form.content"
              class="form-control"
              svg-path="https://unpkg.com/trumbowyg@2.9.4/dist/ui/icons.svg"
              :config="configs.basic"></trumbowyg>
```

Also can you try disabling image optimization by Laravel mix
```js
// webpack.mix.js
mix.options({
  imgLoaderOptions: {
    enable: false
  },
});

```

**Comment by thomaswoj** [comment]
Hmmm, getting a vue error in console when adding <trumbowyg v-model....>,

![image](https://user-images.githubusercontent.com/34551337/36945954-445de49a-1fad-11e8-901a-a2db0ebd3943.png)

**Comment by ankurk91** [comment]
Don't copy my code blindly. All you need to do is add this prop to your component
```
 svg-path="https://unpkg.com/trumbowyg@2.9.4/dist/ui/icons.svg"
```

**Comment by thomaswoj** [comment]
My Apologies, I misunderstood.

Yup - icons are now loading correctly with the workaround. :) 

This should be fine as I don't need the icons locally. 

Many thanks for your help Ankurk, it's greatly appreciated.

**Comment by ankurk91** [comment]
Glad to know.
I will test it with Laravel mix v2.x soon and will post back here.

**Comment by ankurk91** [comment]
I can confirm that this is` img-loader` issue in Laravel-mix.
Disabling image loader fixes this issue.

Here is how to fix this issue:
```
// webpack.mix.js
mix.options({
  imgLoaderOptions: {
    enabled: false
  },
});
```
