### ISSUE TITLE
Base64 plugin not rendering image

### ISSUE THREAD

**Issue by netgfx** [ankurk91/vue-trumbowyg#18]
**I'm submitting a ...**  (check one with "x")
```
[ x] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Trumbowyg version : v2.11.0
* Vue.js version : v2.5.17
* Browser name and version : Chrome latest
* Parcel : v1.10.3

**Current behavior**
Have added the base64 plugin (item exists on the toolbar and working), but the image is not added without any errors on the console.

**Expected behavior**
An image to appear on the text area.

**Minimal reproduction of the problem with instructions**

html
`<trumbowyg v-model="content" v-bind:config="config" class="form-control col-12" name="content"></trumbowyg>`

js
```
import 'trumbowyg/dist/ui/trumbowyg.min.css';
import Trumbowyg from 'vue-trumbowyg';
import '../../../../node_modules/trumbowyg/dist/plugins/base64/trumbowyg.base64.min.js';

Vue.component("trumbowyg", Trumbowyg);

app = new Vue({
                el: wrapperComponent,
                data: {
                    config: {
                        autogrow: true,
                        btnsDef: {
                            // Create a new dropdown
                            image: {
                                dropdown: ['insertImage', 'base64'],
                                ico: 'insertImage'
                            }
                        },
                        // Redefine the button pane
                        btns: [
                            ['viewHTML'],
                            ['formatting'],
                            ['strong', 'em', 'del'],
                            ['superscript', 'subscript'],
                            ['link'],
                            ['image'], // Our fresh created dropdown
                            ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                            ['unorderedList', 'orderedList'],
                            ['horizontalRule'],
                            ['removeformat']
                        ]
                    },
                    content: null
                }
});

**Comment by ankurk91** [comment]
This is an issue with parent library [Trumbowyg](https://github.com/Alex-D/Trumbowyg) itself
It was working fine till v2.9.4

https://jsfiddle.net/py8y56jo/14/

You should report this issue there.

**Comment by netgfx** [comment]
Just to confirm that the JSFiddle posted doesn't work as well.

**Comment by ankurk91** [comment]
Thats what i said mate. 
The jsfiddle was posted for you so that you can test it without vue.js.
