### ISSUE TITLE
Icons missing when using CDN

### ISSUE THREAD

**Issue by jchamb** [ankurk91/vue-trumbowyg#21]
**I'm submitting a ...**  (check one with "x")
```
[X ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

404 is thrown from jsdeilvr for 
https://cdn.jsdelivr.net/npm/vue-trumbowyg@3.4.1/dist/vue-/ui/icons.svg

https://www.jsdelivr.com/package/npm/vue-trumbowyg?path=dist

**Comment by ankurk91** [comment]
icons are not bundled with this (vue-trumbowyg) package.

they comes from the parent package `trumbowyg`
See
https://cdn.jsdelivr.net/npm/trumbowyg@2.13.0/dist/ui/

So the correct url for svg should be
```
https://cdn.jsdelivr.net/npm/trumbowyg@2.13.0/dist/ui/icons.svg
```

When using this package from a CDN, you no need to specify the icon url at all.
See the js fiddle
https://jsfiddle.net/ankurk91/p7xs2jkk/
