### ISSUE TITLE
Support for placeholder?

### ISSUE THREAD

**Issue by san-kumar** [ankurk91/vue-trumbowyg#22]
I'm trying to add a `placeholder` text to this as described here:

https://alex-d.github.io/Trumbowyg/documentation/#placeholder

But adding it as attribute isn't working. It also can't be put in the configuration.

Anyone have any idea on how to do it?

Thanks!

**Comment by ankurk91** [comment]
I could not reproduce it, the placeholder works fine.
```html

  <trumbowyg v-model="content" placeholder="here we go"></trumbowyg>

```
