### ISSUE TITLE
SVG imported as code and not file

### ISSUE THREAD

**Issue by glimow** [ankurk91/vue-trumbowyg#23]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[X] Other, please describe
```

**Tell about your platform**
* Trumbowyg version : auto selected from vue-trumbowyg
* Vue.js version : 2.3.3
* Browser name and version : Electron 1.7.5 (Chromium)
* This package version : 3.4.1

**Current behavior**
When importing `vue-trumbowyg`, webpack imports the svg icons as code instead of svg. 
![image](https://user-images.githubusercontent.com/26530171/53922673-9532da80-4075-11e9-9d81-b40caaf28314.png)
Making the script to fail running in the browser.
**Expected behavior**
The SVG should be imported as a file and not be inserted into the code

My webpack config (extract):

```javascript
{
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'imgs/[name]--[folder].[ext]'
          }
        }
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000,
          name: 'media/[name]--[folder].[ext]'
        }
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        use: {
          loader: 'url-loader',
          query: {
            limit: 10000,
            name: 'fonts/[name]--[folder].[ext]'
          }
        }
      }
```
I am using Webpack 3.5.2 with Electron-Vue setup

**Comment by ankurk91** [comment]
I don't see any issue importing the *.svg icons, here is my config for webpack 4

https://github.com/ankurk91/vue-trumbowyg/blob/1058f9d3d34064e8170147fb0da7bb7cfbc92975/webpack.config.dev.js#L62-L68

Most likely webpack or loader issue.
