### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by warhost** [ankurk91/vue-trumbowyg#25]
Hi,

eventhough I am importing jQuery, I am getting "jQuery is not defined":

```
import jQuery from 'jquery';
import Trumbowyg from 'vue-trumbowyg';  
import 'trumbowyg/dist/ui/trumbowyg.css';
```

Is there something wrong with how I import it?

**Comment by ankurk91** [comment]
Did you followed
https://github.com/ankurk91/vue-trumbowyg/wiki/Webpack

**Comment by warhost** [comment]
Thanks. Works now. Maybe consider adding some more info on the readme.

**Comment by firmanjabar** [comment]
> > Did you followed
> > https://github.com/ankurk91/vue-trumbowyg/wiki/Webpack
> 
> where do i can find webpack.config.js?
> ![2019-10-09](https://user-images.githubusercontent.com/45032367/66495508-e7484c80-eaeb-11e9-8bf4-f5b3de31c839.png)

i just found 72 result in package-lock.json, but dont know where do i can paste this code:
module.exports = {
 // your existing config may go here
module: {
    rules: [
      {
        test: /\.(woff|woff2|eot|ttf|svg)(\?.*$|$)/,
        loader: 'file-loader?name=[name].[ext]?[hash]',
      }

    ]
},
  plugins: [
    new webpack.ProvidePlugin({
       Vue: ['vue/dist/vue.esm.js', 'default'],
      jQuery: 'jquery',
      $: 'jquery',
      'window.jQuery': 'jquery',
    }),
  ],
};
![2019-10-09 (1)](https://user-images.githubusercontent.com/45032367/66495898-9be26e00-eaec-11e9-98a8-c6a5ad6ed4f6.png)

**Comment by firmanjabar** [comment]
> > Did you followed
> > https://github.com/ankurk91/vue-trumbowyg/wiki/Webpack
> 
> where i can find webpack.config.js?
> 
> ![2019-10-09](https://user-images.githubusercontent.com/45032367/66495508-e7484c80-eaeb-11e9-8bf4-f5b3de31c839.png)
> 
> i just found 72 result in package-lock.json, but dont know how to and where i can paste this code:
> 
> ```js
> module.exports = {
>  // your existing config may go here
> module: {
>     rules: [
>       {
>         test: /\.(woff|woff2|eot|ttf|svg)(\?.*$|$)/,
>         loader: 'file-loader?name=[name].[ext]?[hash]',
>       }
> 
>     ]
> },
>   plugins: [
>     new webpack.ProvidePlugin({
>        Vue: ['vue/dist/vue.esm.js', 'default'],
>       jQuery: 'jquery',
>       $: 'jquery',
>       'window.jQuery': 'jquery',
>     }),
>   ],
> };
> ```
> 
> ![2019-10-09 (1)](https://user-images.githubusercontent.com/45032367/66495898-9be26e00-eaec-11e9-98a8-c6a5ad6ed4f6.png)

Problem Solved, just adding vue.config.js on root then write the plugin:

```javascript
var webpack = require("webpack");

module.exports = {
    configureWebpack: {
        plugins: [
            new webpack.ProvidePlugin({
                $: 'jquery',
                jquery: 'jquery',
                'window.jQuery': 'jquery',
                jQuery: 'jquery'
            })
        ]
    }
}
```
