### ISSUE TITLE
Add custom html.

### ISSUE THREAD

**Issue by vkiranananda** [ankurk91/vue-trumbowyg#32]
Hello!

I want to add custom HTML where the cursor is. How to do it?

Thank you!

**Comment by ankurk91** [comment]
Please ask such questions at
https://github.com/Alex-D/Trumbowyg

**Comment by vkiranananda** [comment]
Ок. How I get access to $('#my-editor') ?
```
$('#my-editor').trumbowyg('execCmd', {
	cmd: 'insertText',
	param: 'TextToInsert',
	forceCss: false,
});```

**Comment by ankurk91** [comment]
You can add a `ref="editor"` to component and then access it like
```
// In your component
this.$refs.editor.el.trumbowyg();
```

**Comment by vkiranananda** [comment]
Thanks @ankurk91
