### ISSUE TITLE
Update Trumbowyg to v2.20.0

### ISSUE THREAD

**Issue by atmediauk** [ankurk91/vue-trumbowyg#35]
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[x] Other, please describe
```
Just wondering if it is possible to update the package deps as some new features were recently added to Trumbowyg v2.20.0

**Comment by ankurk91** [comment]
Package.json version constraints already allow you to install requested version
https://github.com/ankurk91/vue-trumbowyg/blob/273910fc82c272f1aa3a0264b9802791e1bd0b6b/package.json#L38
