### ISSUE TITLE
Can`t set min-height of the editor

### ISSUE THREAD

**Issue by axeh** [ankurk91/vue-trumbowyg#37]
**I'm submitting a ...**
[x] Bug report => search github for a similar issue or PR before submitting

**Current behaviour**
It seems that div containing class trumbowyg-editor has height style property set.
Because of that, you can`t specify min-height of the editor.

On official demo, you can inspect html and see it.

**Comment by ankurk91** [comment]
This issue is not related to vue component, please report your issue here
https://github.com/Alex-D/Trumbowyg
