### ISSUE TITLE
TypeError: this.el.trumbowyg is not a function

### ISSUE THREAD

**Issue by NorWilhelm** [ankurk91/vue-trumbowyg#38]
Hi Ankurk91,

I would love to use your Vue-component, but I keep getting this error:

**TypeError: this.el.trumbowyg is not a function**

 In my troubleshooting and "googleling", I have seen alot of writing about the webpack config which should be localized under "node_modules/"; However according to [Vue's official documentation](https://cli.vuejs.org/guide/webpack.html#simple-configuration), the config should be modified under **Vue.config.js**. Not quite sure how to config this file.

I don't know for sure if i'm using webpack or laravel... I'm just using vue as it is....
BTW. I have installed and included jQuery. 

Perhaps you can give me some advise?

**Comment by ankurk91** [comment]
I cannot help unless i know if you are using webpack or laravel.
Sorry, Github is not fir noobs. 

We maintainers also do our jobs to earn money, please help us to debug your issues by providing information about your stack. 

Thanks
