### ISSUE TITLE
embed plugin issue 

### ISSUE THREAD

**Issue by uwejan** [ankurk91/vue-trumbowyg#39]
Hi, i just made a fresh install. am getting the following error.
`trumbowyg@2.21.0 requires a peer of jQuery@>=1.8 but none is installed. You must install peer dependencies yourself.`
advice please?

**Comment by uwejan** [comment]
seemed to work against the warning, but `frame` videos do not render, and video urls do not work too.

**Comment by ankurk91** [comment]
Did you configure `trumbowyg.pasteembed` Plug-in?

Can you share a js fiddle?

**Comment by ankurk91** [comment]
@uwejan 
Can you try to paste this url
```
https://www.youtube.com/watch?v=dQw4w9WgXcQ
```
on
https://ankurk91.github.io/vue-trumbowyg/

You will found it is working fine, it was not working on js-fiddle for some reasons.

**Comment by uwejan** [comment]
hi @ankurk91 , it dose work your example, mine still not.
i get this warning while installing the editor, is it safe to ignore it?
`trumbowyg@2.21.0 requires a peer of jQuery@>=1.8 but none is installed. You must install peer dependencies yourself.`

**Comment by uwejan** [comment]
@ankurk91 Thank you. all good.
