### ISSUE TITLE
error on adding component to the page

### ISSUE THREAD

**Issue by iwebnaut** [ankurk91/vue-trumbowyg#4]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```
I just installed the editor in my project and init it like this:

    <trumbowyg :id="'editor-'+uniqueId" v-model="blockContent"></trumbowyg>

and I get this when I add it to the page
[Vue warn]: Error in mounted hook: "TypeError: this.el.trumbowyg is not a function"
no toolbar is visible and only textarea is visible.

**Comment by ankurk91** [comment]
Are you using webpack?
If you can please check for this config
```js
new webpack.ProvidePlugin({
      Vue: 'vue',
      jQuery: 'jquery',
      $: 'jquery',
    }),
```
https://github.com/ankurk91/vue-trumbowyg/blob/master/webpack.config.dev.js

**Comment by iwebnaut** [comment]
hmm I have it in package.json included like this:


  "dependencies": {
     ...some other stuff here...
    "vue-trumbowyg": "^1.0.3",

I'm not sure about stuff you mention and where to check for it.

**Comment by ankurk91** [comment]
If you are not using webpack then you need to include jQuery on your html 
Instructions can be found in readme file

**Comment by iwebnaut** [comment]
I am using webpack I belive, whatever is Laravel configured out of box is what I am using and I belive its webpack. And I have jQuery in my html as well.

**Comment by iwebnaut** [comment]
check this: https://maxniko.tinytake.com/sf/MTk4NDQ1Ml82Mjc5Mjgw

**Comment by iwebnaut** [comment]
btw totaly not related question for this report, are you available for freelance? I may have work for you if you are. Let me know and if you want delete this question :)

**Comment by ankurk91** [comment]
Okay, then you need to read this
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/autoloading.md

**Comment by ankurk91** [comment]
Ha ha, sorry I work 9 to 7 already.
I do open source for fun.

**Comment by iwebnaut** [comment]
great thanks for your help and your contibutions to the vue community with these components :) anyways I do have opensource project in works but if you are busy then well good luck :)

**Comment by ankurk91** [comment]
I will write a small wiki on how to use this package in Laravel mix.
Closing; feel free to re-open.

**Comment by iwebnaut** [comment]
you are one of a kind! :)

**Comment by iwebnaut** [comment]
Btw I do not have this file in my project: webpack.mix.config.js Do I have to manyally create it and where should I put it?

inside my webpack.mix.js I have this:

mix.webpackConfig({
  resolve: {
    alias: {
      components: path.resolve(__dirname, './resources/assets/js/components'),
      utils: path.resolve(__dirname, './resources/assets/js/utils')
    }
  },
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]lib[\/\\]locale[\/\\]lang[\/\\]zh-CN/, 'element-ui/lib/locale/lang/en'),
    new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]src[\/\\]locale[\/\\]lang[\/\\]zh-CN/, 'element-ui/src/locale/lang/en'),
    new webpack.NormalModuleReplacementPlugin(/element-ui[\/\\]packages[\/\\]scrollbar/, 'element-ui/lib/scrollbar')
  ]
});

is that part of the same thing, could I put that code in there or do I need this config file?

**Comment by ankurk91** [comment]
Ah, there was a typo, should be fixed now.
There is only one file `webpack.mix.js` that need to be configured.

**Comment by iwebnaut** [comment]
battleship operational: https://maxniko.tinytake.com/sf/MTk4NjE0MF82MjgzMzgy

thank you for your help!
