### ISSUE TITLE
Strikethrought is irreversable

### ISSUE THREAD

**Issue by remokessler** [ankurk91/vue-trumbowyg#43]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* Trumbowyg version : 3.6.0
* Vue.js version : 2.6.11
* Browser name and version : Chrome  81.0.4044.138
* This package version : 3.6.0?

**Current behavior**
When I strikethrough a word and want to reverse it I cannot do so neighter with hitting the button again nor with the remove format function.

**Expected behavior**
I would expect it to reverse the strikethrought so that no del tag is in the selected area.

**Minimal reproduction of the problem with instructions**
1. Write a word or sentence
2. Strikethrough the word with the delete button.
3. Press said button again.
Nothing happens

Thanks for looking at this issue!

Best regards from Switzerland
Remo

**Comment by ankurk91** [comment]
Report your issue here
https://github.com/Alex-D/Trumbowyg
