### ISSUE TITLE
How can i extend lang file in Persian (fa) mode? 

### ISSUE THREAD

**Issue by hbsoftco** [ankurk91/vue-trumbowyg#46]
Hi
I use some plugins, some words are not in the translation file, how can I extend the language file?
Like this https://github.com/Alex-D/Trumbowyg/issues/1142#event-3509141803 
I did according to alex reply, but nothing was displayed in vue-trumbowyg.

**Comment by ankurk91** [comment]
@hbsoftco 
Can you show me a working fiddle ?

You can start from here
https://jsfiddle.net/ankurk91/p7xs2jkk/

**Comment by ankurk91** [comment]
@hbsoftco 
I was able to make it work, see here

https://jsfiddle.net/8hmbf1ak/
