### ISSUE TITLE
Editing bugs

### ISSUE THREAD

**Issue by iwebnaut** [ankurk91/vue-trumbowyg#5]
**I'm submitting a ...**  (check one with "x")
```
[x ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```
Latest version of everything used, I get this weird behaviour:

https://maxniko.tinytake.com/sf/MTk4NjM0MV82MjgzNzYz

It appearsh whean using headings with paragraphs.

**Comment by ankurk91** [comment]
Can you please setup a jsfiddle. And write steps to reproduce.
**Vue js**
https://jsfiddle.net/ankurk91/p7xs2jkk/

**Plain js**
https://jsfiddle.net/ankurk91/py8y56jo/

Please fork them and then make your changes.
Then paste your new fiddle links here.

**Comment by iwebnaut** [comment]
Thank you. I made a video for you that will help you understand the problem a bit better:

https://maxniko.tinytake.com/sf/MTk4NjUxN182Mjg0MTc1

Since it's not easy to recrate it using jsfiddles you provided as you will see in video, I am instead sending you the video. Let me know your thoughts :)

**Comment by iwebnaut** [comment]
seems you are not able to view my videos, please let me know if you could view above video and if not I will upload it elsewhere where you can download it and watch it since it's not easy to show you this bug directly in the jsfiddle but I demonstrate it clearly in the video

**Comment by ankurk91** [comment]
As said I am unable to play videos.
Video does help in understanding what's going on.
Can you create GIF using this small free tool
https://www.cockos.com/licecap/

Also can you confirm that you can reproduce same on given jsfiddle?

**Comment by iwebnaut** [comment]
hi on the link to the video I provided, can you see a download button? Perhaps if you try that instead of playing the video directly. It's an mp4 file which you should be able to play? I can't make a gif, I made 3-4 minute video speaking and showing you the bug, gif would be probably few GB and no sound. Let me know if you can download the video and view it on your machine?

**Comment by iwebnaut** [comment]
I uploaded it to youtube for you:

https://www.youtube.com/watch?v=RhsPfcOnnTo
