### ISSUE TITLE
how to use color plugin

### ISSUE THREAD

**Issue by iwebnaut** [ankurk91/vue-trumbowyg#6]
**I'm submitting a ...**  (check one with "x")
```
[x ] Other, please describe
```

How do I use plugins, I need to use color plugin but I can't do this:
https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-colors

    <script src="node_modules/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css"></script>
    <script src="node_modules/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js"></script>

since node_modules is not distributed with my project. How can I make the color plugin available to the thrumbowyg editor withouth doing the above? Can I import it somehow inside my vue app?

**Comment by ankurk91** [comment]
Color Plugin example can be found here
https://github.com/ankurk91/vue-trumbowyg/blob/master/examples/App.vue

**Comment by ankurk91** [comment]
```js
import 'trumbowyg/dist/plugins/colors/trumbowyg.colors';

  import 'trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css'
  ```
Yes you can import any plugin.
