### ISSUE TITLE
insert image not working

### ISSUE THREAD

**Issue by iwebnaut** [ankurk91/vue-trumbowyg#7]
**I'm submitting a ...**  (check one with "x")
```
[ ] Feature request
```
Can't paste in the image, there is no input box visible:

Check the video here
https://maxniko.tinytake.com/sf/MTk4NjQzNV82Mjg0MDE5

Image
https://maxniko.tinytake.com/sf/MTk4NjQ0Ml82Mjg0MDI2

**Comment by ankurk91** [comment]
I am not able to play any of your video.
It shows me error saying - Unable to load file.
Please write steps or create a gif

**Comment by ankurk91** [comment]
Does original [trumborg](https://alex-d.github.io/Trumbowyg/)
 supports pasting images?
If so does it requires any additional plugin to configured first hand?
Or
Does it uploads to server as soon as you drop?
I don't have any of answer right now, I will look in to that.

**Comment by ankurk91** [comment]
There is dedicated Plugins for image handling,
You are looking for this one.

https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-pasteimage

**Comment by iwebnaut** [comment]
I do not think image plugin is needed for this, that plugin is used to insert image object into editor. I am just trying to use simple instert image with url as you could see on the screenshot, no plugin is needed for that since its simple html and browser renders it.

check the video: https://youtu.be/5Q_-iAdTwvY

**Comment by iwebnaut** [comment]
also check the video of how it works in standard trumborg editor:

https://youtu.be/f0H1ATDDNNo

**Comment by iwebnaut** [comment]
just to add more detail, its not just image insert that is not working, even simple insert url has same problem. I'm not sure why, it can't be my app's css messing this up, I've checked for that and did not find any conflicts

**Comment by ankurk91** [comment]
Insert image via URL feature is working for me fine. (see GIF)
![vue-trumbowyg-image-insert](https://user-images.githubusercontent.com/6111524/30948937-12f3bbde-a431-11e7-963d-972b3365960f.gif)

Something is wrong with your CSS, the insert image dialog in your video is appearing different than original.
